name: GitHub PR 생성 시 Notion 업데이트

on:
  pull_request:
    types: [opened, closed, merged]

jobs:
  notion_pr_update:
    runs-on: ubuntu-latest
    steps:
      - name: Notion에 PR 정보 업데이트
        run: |
          curl -X PATCH "https://api.notion.com/v1/pages/${{ secrets.NOTION_PR_PAGE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Notion-Version: 2022-06-28" \
          -H "Content-Type: application/json" \
          --data '{
            "properties": {
              "GitHub 풀 리퀘스트": {
                "relation": [{ "id": "${{ github.event.pull_request.id }}" }]
              },
              "Status": { 
                "status": { "name": "${{ github.event.pull_request.state }}" } 
              }
            }
          }'
